### ISSUE TITLE
Support for indented syntax

### ISSUE THREAD

**Issue by matiassingers** [symdiff/symdiff-sass#1]
Add support for parsing of indented syntax.

Currently you are doing a `grunt.file.read` and passing the string. This is not a good idea for Sass, since it'll break all import paths etc.

**Comment by prayerslayer** [comment]
Okay, so please bear with me, because I hardly use SASS (indented syntax) or Grunt.

What exactly is the problem here? It’s not that `grunt.file.read` loses the indentation of a file, because it doesn’t (…right?). Is the problem that SASS tries to do additional magic (resolving file imports)? If so, would the problem be solved if you could pass options such as `includePaths` to the plugin (see [node-ass API](https://www.npmjs.com/package/node-sass#data))?

Because I really do not want to introduce the symdiff css/template plugins to the concept of files. They should be as stupid as possible.

In an ideal world there would be a SASS parser, producing a SASS AST. Then we wouldn’t even have to care about file imports here (because we shouldn’t, we’re only interested in class definitions and while you can "import" classes via mixins etc it wouldn’t matter if you pass all source files through the plugin). And we would not need to resort to this hack.

Edit: Ah look, now that I searched again I found [this](https://github.com/tonyganch/gonzales-pe). Worth looking into, even though it’s old and might not support newer SASS features.

**Comment by matiassingers** [comment]
I just noticed because I had some older projects using the indented syntax(`.sass`), I ended up just passing a compiled CSS file to symdiff instead - was much simpler.

So there is a couple of issues with the way this currently works:
1. For node-sass to compile indented syntax it needs to be passed the option `indentedSyntax: true`
2. Imports will not work when the data string is just passed to the `sass.renderSync()`
3. Variables from other Sass files will also not work

It'll probably work if you only have Sass files that have no imports, sharing of global variables etc. - but then why use Sass?

``` sh
{
  "status": 1,
  "file": "stdin",
  "line": 1,
  "column": 9,
  "message": "file to import not found or unreadable: vendor/ionic/ionic\nCurrent dir: "
}
```

---

I think an easier approach would be to either:
1. Get people to compile and build their Sass themselves, to ensure all imports etc. are done correctly
2. Pass filepaths instead of content

Interesting with the AST actually, might be a pretty good solution.

**Comment by prayerslayer** [comment]
> I ended up just passing a compiled CSS file to symdiff instead - was much simpler.

Yeah, that always works. Because there’s a decent CSS parser available.

> For node-sass to compile indented syntax it needs to be passed the option indentedSyntax: true

I see.

> Imports will not work when the data string is just passed to the sass.renderSync()

But they will work if you define `includePaths` additionally, right?

> Variables from other Sass files will also not work

Should we care? Can you create classes from variables? Or do we **have** to care because we’re using `renderSync` and it would break?

> Pass filepaths instead of content

No. :grin: 

I will look into it, either the gonzales-pe parser does it’s job or I have to change the plugin API so that you can pass options to it (would hate to do that).

**Comment by matiassingers** [comment]
> But they will work if you define includePaths additionally, right?

Might work, didn't test that out - but also a lot of overhead hassle.

> Should we care? Can you create classes from variables? Or do we have to care because we’re using renderSync and it would break?

Yeah as long as it's using `renderSync` it'll break on references to variables that doesn't exist. It might be possible to ignore the errors, but not sure about this.

> No. 
> 
> I will look into it, either the gonzales-pe parser does it’s job or I have to change the plugin API so that you can pass options to it (would hate to do that).

I think if gonzales works, then great.

Passing options seems annoying as well.

**Comment by prayerslayer** [comment]
Newest version (0.0.5) uses `gonzales-pe` and should support SASS and SCSS equally well. I will close this, if you have problems please open up a new issue.

**Comment by matiassingers** [comment]
Awesome :+1:
